// Step 1: Import Java classes Arrays, Random, and Scanner
import java.util.Arrays;
import java.util.Random;
import java.util.Scanner;
/**
 * A class to generate a random int array then call static
 * methods to sort and display the array elements.
 * 
 * Step 2: Enter your name for @author and today's date for @version
 * @author  Froilan Zarate
 * @version 11-10-2022
 */
public class StaticMethodApp
{
   public static void main(String[] args)
   {
        Scanner in = new Scanner(System.in);
        
        System.out.print("Enter an integer: ");
        
        // Step 3: While the next input token is not an integer
        //               Read the input token 
        //               Display a message
        //                  Sample message, assuming the input is Java
        //                  Not an integer: "Java"
        //               Display the same promt again
        while (!in.hasNextInt())
        {
            System.out.println("Not an integer: \"" + in.next() + "\"");
            System.out.print("Enter an integer: ");
        }
             
        // Step 4: Read the integer and store it in a variable 
        int seed = in.nextInt();
        
        // Step 5: Create a Random object using the input integer
        Random random = new Random(seed);

        System.out.print("Enter the array length: ");
        int length = in.nextInt();
        
        // Step 6: Create an array of int of 
        //         the specified length
        int[] intArray = new int[length];
        
        System.out.print("Enter the low range limit: ");
        int lowLimit = in.nextInt();
        
        System.out.print("Enter the high range limit: ");
        int highLimit = in.nextInt();
        
        // Step 7: Use a for loop to fill the array with random 
        //         integers generated by the Random generator 
        //         created in Step 5 in the range [lowLimit, highLimit]
        for (int i = 0; i < length; i ++)
        {
            intArray[i] = random.nextInt(highLimit - lowLimit  + 1) + lowLimit;
        }
            
        System.out.println("Before sorting:");
        
        // Step 8: Call static method toString() of Arrays to  
        //         display all elements of the array
        System.out.println(Arrays.toString(intArray));
        
        // Step 9: Call a static method of Arrays to sort
        //         all elements of the array
        // You need to search the Java Class Libraries 
        // to find the static method needed.
        Arrays.sort(intArray);
        
        System.out.println("After sorting:");

        // Step 10: Call static method toString() of Arrays to  
        //          display all elements of the array again
        System.out.println(Arrays.toString(intArray));
   }
}
