// Step 1: import Java classes Scanner, Random, and ArrayList
import java.util.Scanner;
import java.util.Random;
import java.util.ArrayList;
/**
 * Input two integers, one as the number of frogs, another
 * as the seed for a random generator, then create the 
 * specified number of frogs using the random generator 
 * to get the weights and store them in an array list.
 * Finally, swap the first and the last frogs, and use
 * the enhanced for loop to print out all frogs before
 * and after swapping.
 *
 * Step 2: Enter your name for @author and today's date for @version
 * @author  Froilan Zarate
 * @version 10-20-2022
 */
public class FrogListApp
{
    public static void main(String[] args)
    {
        final int MIN_WEIGHT = 1;
        final int MAX_WEIGHT = 25;
        
        // Step 3: Create an array list to store Frog objects
        ArrayList<Frog> frogList = new ArrayList<Frog>();
        

        // Step 4: Create a Scanner object
        Scanner in = new Scanner(System.in);
        
        
        // Step 5: Read an integer as the number of frogs
        //         using prompt "Enter the number of frogs: "
        System.out.print("Enter the number of frogs: ");
        int frogNumber = in.nextInt();
        
        // Step 6: Read an integer as the random generator seed
        //         using prompt 
        //         "Enter an integer as the random generator seed: "
        System.out.print("Enter an integer as the random generator seed: ");
        int seed = in.nextInt();

        // Step 7: Create a Random object using the input seed
        Random random = new Random(seed);
        
        // Step 8: Use a for loop to create the specified number
        //         of frogs and add them to the array list.
        //         The weights of the frogs must be in the range
        //         [MIN_WEIGHT, MAX_WEIGHT] and be generated by
        //         the Random object created in Step 7
        Frog frog;
        for (int i = 1; i <= frogNumber; i ++)
        {
            frog = new Frog(random.nextInt(MAX_WEIGHT - MIN_WEIGHT + 1) + MIN_WEIGHT);
            frogList.add(frog);
        }
        
        System.out.println("All frogs before swapping:");

        // Step 9: Use the enhanced for loop to print
        //         out all frogs in the list, one per line
        for (Frog aFrog: frogList)
        {
            System.out.println(aFrog);
        }
        
        // Step 10: Calculate the index of the last frog 
        //          in the list and store it in a variable
        int frogLastNumber = frogList.size() - 1;
        
        // Step 11: Swap the first and the last frogs in the list
        frog = frogList.get(frogLastNumber);
        frogList.set(frogLastNumber, frogList.get(0));
        frogList.set(0, frog);
        
        
        System.out.println("All frogs after swapping:");
        
        // Step 12: Use the enhanced for loop to print
        //          out all frogs in the list, one per line
        for (Frog aFrog: frogList)
        {
            System.out.println(aFrog);
        }
        
        
    }
}
